"""Validate semantic programs and delegate emission to an explicit target."""

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, runtime_checkable

from .configuration import validate_device_usage
from .devices import DeviceBindings
from .diagnostics import CompilationError, Diagnostic, IRValidationError
from .ir import Program, validate
from .specialization import specialize


@dataclass(frozen=True, kw_only=True)
class Artifact:
    """Target-generated bytes and their format description.

    Attributes:
        content: Complete output bytes, without implicit text decoding.
        media_type: MIME type chosen by the target.
        suffix: Recommended filename extension, including its leading dot."""

    content: bytes
    media_type: str
    suffix: str


@runtime_checkable
class Target(Protocol):
    """Contributor interface consumed by the target-independent compiler."""

    @property
    def target_id(self) -> str:
        """Identify the platform/format represented by emitted artifacts."""
        ...

    def resolve_devices(self, program: Program) -> DeviceBindings:
        """Return trusted deployment facts for the authored program's resources."""
        ...

    def validate(self, program: Program) -> tuple[Diagnostic, ...]:
        """Return target restrictions after specialization; an empty tuple passes."""
        ...

    def emit(self, program: Program) -> Artifact:
        """Generate bytes from the validated, specialized high-level program."""
        ...


@dataclass(frozen=True, kw_only=True)
class CompileResult:
    """Compilation evidence and output for one explicit target.

    Attributes:
        semantic_ir: Original authored program, before device specialization.
        specialized_ir: High-level program selected for the supplied bindings.
        target_id: Target's format/platform identity.
        artifact: Target output; backend-private storage stays outside both IRs.
        diagnostics: Empty for results returned by compile_ir; any validation
            diagnostic currently raises an exception instead of returning a result.
    """

    semantic_ir: Program
    specialized_ir: Program
    target_id: str
    artifact: Artifact
    diagnostics: tuple[Diagnostic, ...] = ()

    def write(self, path: str | Path) -> Path:
        """Write artifact bytes, creating parent directories and replacing an existing file.

        Args:
            path: Destination filename; no extension is added automatically.

        Returns:
            The supplied destination as a Path.

        Raises:
            OSError: The destination cannot be created or written."""
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(self.artifact.content)
        return destination


def compile_ir(program: Program, *, target: Target) -> CompileResult:
    """Validate, specialize and compile a program without parsing Python source.

    Args:
        program: Authored semantic IR from any frontend or JSON.
        target: Explicit target implementing binding resolution, validation and emission.

    Returns:
        Both semantic programs and the emitted artifact.

    Raises:
        TypeError: The target is missing a required member, or the returned bindings
            are not DeviceBindings. Argument and return types are a static contract,
            checked by a type checker rather than here.
        IRValidationError: The authored or specialized IR is invalid.
        CompilationError: Binding, configuration or target validation fails.

    Neither XML assumptions nor backend-private state belong in this pipeline."""
    if not isinstance(target, Target):
        raise TypeError(
            "target must implement target_id, resolve_devices(program), validate(program) and emit(program)."
        )
    diagnostics = validate(program)
    if diagnostics:
        raise IRValidationError(diagnostics)
    bindings = target.resolve_devices(program)
    specialized = specialize(program, bindings=bindings)
    diagnostics = validate_device_usage(specialized, bindings)
    if diagnostics:
        raise CompilationError(diagnostics)
    diagnostics = target.validate(specialized)
    if diagnostics:
        raise CompilationError(diagnostics)
    artifact = target.emit(specialized)
    return CompileResult(semantic_ir=program, specialized_ir=specialized, target_id=target.target_id, artifact=artifact)
