"""Typed semantic IR, validated JSON interchange and frontend-neutral diagnostics."""

from .codec import from_dict, from_json, to_dict, to_json
from ..diagnostics import Diagnostic, IRValidationError, SourceSpan
from .types import ScalarType
from .model import (
    AgitatorResource,
    SetAgitation,
    StopAgitation,
    Assignment,
    Binary,
    BinaryOp,
    Call,
    Expression,
    FunctionIR,
    If,
    InputBinding,
    Literal,
    OutputBinding,
    Program,
    Reference,
    Statement,
    Unary,
    UnaryOp,
    Variable,
    VariableRole,
    While,
)
from .validation import validate

__all__ = [
    "AgitatorResource",
    "SetAgitation",
    "StopAgitation",
    "Assignment",
    "Binary",
    "BinaryOp",
    "Call",
    "Diagnostic",
    "Expression",
    "FunctionIR",
    "IRValidationError",
    "If",
    "InputBinding",
    "Literal",
    "OutputBinding",
    "Program",
    "Reference",
    "ScalarType",
    "SourceSpan",
    "Statement",
    "Unary",
    "UnaryOp",
    "Variable",
    "VariableRole",
    "While",
    "from_dict",
    "from_json",
    "to_dict",
    "to_json",
    "validate",
]
