"""Typed semantic IR, validated JSON interchange and frontend-neutral diagnostics."""

from sciloom.core.diagnostics import Diagnostic, IRValidationError, SourceSpan
from .codec import from_dict, from_json, to_dict, to_json
from .device_contracts import CommandContract, CommandParameter, DeviceTypeContract, PropertyContract
from .model import (
    Assignment,
    Binary,
    BinaryOp,
    Call,
    CanWrite,
    CommandArgument,
    ConfigureProperty,
    DeviceCommand,
    DeviceIf,
    DevicePredicate,
    DeviceResource,
    Expression,
    FunctionIR,
    If,
    InputBinding,
    IsDevice,
    ListGet,
    ListLength,
    ListLiteral,
    ListSet,
    Literal,
    LogValue,
    Notify,
    OutputBinding,
    Program,
    Reference,
    StartAgitation,
    Statement,
    StopAgitation,
    SupportsOperation,
    TextLength,
    TextSplitPart,
    TextTrim,
    Unary,
    UnaryOp,
    Variable,
    VariableRole,
    While,
)
from .types import ListType, ScalarType, ValueType
from .validation import validate

__all__ = [
    "LogValue",
    "Notify",
    "TextLength",
    "TextTrim",
    "TextSplitPart",
    "PropertyContract",
    "CommandContract",
    "CommandParameter",
    "DeviceTypeContract",
    "DeviceResource",
    "ConfigureProperty",
    "StartAgitation",
    "DeviceCommand",
    "CommandArgument",
    "CanWrite",
    "SupportsOperation",
    "IsDevice",
    "DeviceIf",
    "DevicePredicate",
    "StopAgitation",
    "Assignment",
    "Binary",
    "BinaryOp",
    "Call",
    "Diagnostic",
    "Expression",
    "FunctionIR",
    "IRValidationError",
    "If",
    "InputBinding",
    "Literal",
    "ListType",
    "ValueType",
    "ListLiteral",
    "ListLength",
    "ListGet",
    "ListSet",
    "OutputBinding",
    "Program",
    "Reference",
    "ScalarType",
    "SourceSpan",
    "Statement",
    "Unary",
    "UnaryOp",
    "Variable",
    "VariableRole",
    "While",
    "from_dict",
    "from_json",
    "to_dict",
    "to_json",
    "validate",
]
