"""Immutable 0.2.0 v4 documents remain readable and executable.

Fixtures were captured before the wire-contract refactor at the commit recorded
in fixtures/v4/manifest.json. They are not regenerated by examples or tests.
"""

import hashlib
import json
from pathlib import Path

import pytest

from sciloom.core.interpreter import Interpreter
from sciloom.units import rpm
from . import from_json, to_json

FIXTURES = Path(__file__).with_name("fixtures") / "v4"
MANIFEST = json.loads((FIXTURES / "manifest.json").read_text())


@pytest.mark.parametrize("name", MANIFEST["programs"])
def test_old_v4_canonical_bytes(name):
    original = (FIXTURES / f"{name}.json").read_bytes()
    assert hashlib.sha256(original).hexdigest() == MANIFEST["programs"][name]["json_sha256"]
    assert to_json(from_json(original.decode())).encode() == original


@pytest.mark.parametrize(
    "name,inputs,outputs",
    [
        ("list_ir", {"values": [1.0, 2.0]}, {"result": (9.0, 2.0)}),
        ("non_zero_array_min", {"values": [0.0, 4.0, 2.0, 0.0]}, {"minimum": 2.0}),
        ("non_zero_array_min", {"values": []}, {"minimum": 999999.0}),
        ("function_call", {}, {}),
    ],
)
def test_old_v4_reference_results(name, inputs, outputs):
    program = from_json((FIXTURES / f"{name}.json").read_text())
    result = Interpreter(program).run(inputs=inputs)
    assert result.outputs == outputs
    if name == "function_call":
        variable = next(v for f in program.functions for v in f.variables if v.name == "result")
        assert result.state[program.entry_function_id][variable.node_id] == 2.5


def test_old_v4_device_state():
    program = from_json((FIXTURES / "agitation_ir.json").read_text())
    session = Interpreter(program)
    started = session.run(inputs={"shaker_speed": 600 * rpm, "enabled": True})
    stopped = session.run(inputs={"shaker_speed": 0 * rpm, "enabled": False})
    resource = program.resources[0].node_id
    assert started.resources[resource].enabled
    assert not stopped.resources[resource].enabled
    assert stopped.resources[resource].configuration == {"speed": 600 * rpm}
